module.exports.groupService = require('./group.service')
module.exports.memberService = require('./member.service')
module.exports.attendanceService = require('./attendance.service')
module.exports.authenticationService = require('./authentication.service')
module.exports.dataService = require('./data.service')
module.exports.userService = require('./user.service')
module.exports.notificationService = require("./notification.service")
module.exports.departmentService = require("./department.service")
